#include "exception.h"

void try_catch_block(bool (*try_fun)(va_list args), void (*catch_fun)(va_list args), ...)
{
	
}